diamondhands-dev/shiro-backend

.github/workflows/rust.yaml, src/main.rs
=> Pass `cargo clippy` in CI.

Cargo.toml, src/healthz.rs, src/main.rs
=> Add tests for `/healthz`.

.github/workflows/rust.yaml
=> Start collecting code coverages with Codecov.

.github/workflows/rust.yaml, Cargo.toml, src/keys.rs, src/main.rs
=> Provide a `/keys` PUT endpoint.

.github/workflows/rust.yaml, Cargo.toml, src/keys.rs, src/lib.rs, src/opts.rs
=> Apply a Bitcoin network via a command-line option.

src/keys.rs, src/main.rs
=> Add `/keys` POST endpoint.

src/main.rs, src/opts.rs, src/wallet/mod.rs
=> Support `WalletState` that holds `wallet_data`.

.github/workflows/audit-check-on-push.yaml
=> Enable audit-check on GH-Actions.

src/main.rs, src/wallet/dir.rs, src/wallet/mod.rs
=> Add an GET endpoint `/wallet/dir`.

.github/workflows/rust.yaml, Cargo.toml, src/keys.rs, src/opts.rs, src/wallet/dir.rs, src/wallet/mod.rs
This is a hot fix. No issue bound.
=> Use `signet` for tests.

Cargo.toml
=> Track rgb_lib on the main branch.

src/wallet/go_online.rs, src/wallet/mod.rs
=> Add the PUT endpoint for `/wallet/go_online`.

src/wallet/address.rs, src/wallet/mod.rs
=> Add `/wallet/address` GET endpoint.

src/wallet/go_online.rs, src/wallet/mod.rs
=> Refactor `online` related code.

src/wallet.rs
=> Store `Online` into `ShiroWallet`.

src/wallet.rs, src/wallet/unspents.rs
=> Implement `/wallet/unspents` API endpoint.

src/wallet.rs, src/wallet/assets.rs
=> Implement `/wallet/assets` API endpoint.

src/wallet.rs, src/wallet/assets.rs, src/wallet/issue.rs, src/wallet/issue/rgb20.rs
=> Implement `/wallet/issue/rgb20` API endpoint.

src/wallet.rs, src/wallet/utxos.rs
=> Implement `/wallet/utxo` API endpoint.

src/wallet/issue/rgb20.rs, src/wallet/utxos.rs
Fix test for `/wallet/issue/rgb20` (by @zoedberg diamondhands-dev/shiro-backend#63 )
=> Refine a test for `/wallet/issue/rgb20`.

src/wallet.rs, src/wallet/issue/rgb20.rs, src/wallet/transfers.rs
=> Implement `/wallet/transfers` API endpoint.

Cargo.toml, src/wallet.rs, src/wallet/asset_balance.rs
=> Implement `/wallet/asset_balance` API endpoint.

src/wallet.rs, src/wallet/blind.rs
=> Implement `/wallet/blind` API endpoint.

src/wallet.rs, src/wallet/refresh.rs
=> Implement `/wallet/refresh` API endpoint.

src/wallet.rs, src/wallet/send.rs
=> Implement `/wallet/send` API endpoint.

src/main.rs, src/wallet/blind.rs
=> Add API endpoints to the production binary.

.github/workflows/docker.yaml, Dockerfile
=> Start CI for docker images.

.github/workflows/docker.yaml
=> Enable to build container images.

Cargo.toml, src/main.rs
=> Support CORS.

.cargo/config.toml, Dockerfile
=> Fix build failed by OOM.

.dockerignore
=> Add .dockerignore .

src/main.rs
And add `accept-encoding` and `content-length` to allowed headers.
=> Add OPTIONS to allowed methods.

src/main.rs
See also: https://stackoverflow.com/questions/74867363/actix-cannot-start-server-service-0
=> Stop using `Cors.allowed_origin("*").

Cargo.toml, src/main.rs, src/wallet/transfers.rs
=> Add DELETE endpoint for /wallet/transfer .

Cargo.toml
=> Bump the version to 0.3.0 .

Cargo.toml
=> Bump to 0.4.0.

README.md, src/main.rs
This PR fixes https://github.com/diamondhands-dev/shiro-backend/issues/101 and also makes some README adjustments
=> Fix issues with acquiring DB lock
